name: CI Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  frontend-ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./CI-frontend/frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build frontend
        run: npm run build

  backend-ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./CI-backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build backend
        run: mvn clean package -DskipTests

  docker:
    needs:
      - frontend-ci
      - backend-ci

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build frontend image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest ./CI-frontend/frontend

      - name: Build backend image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:latest ./CI-backend

      - name: Push frontend image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest

      - name: Push backend image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest